name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push headless
        uses: docker/build-push-action@v2
        with:
          context: ./headless
          platforms: linux/arm64,linux/amd64
          push: true
          tags: linkuistics/devanyware-headless:latest
      -
        name: Build and push headfull
        uses: docker/build-push-action@v2
        with:
          context: ./headfull
          platforms: linux/arm64,linux/amd64
          push: true
          tags: linkuistics/devanyware-headfull:latest
